### ISSUE TITLE
Angular FOI Form OpenShift Dev Environment Readiness Checks Failing

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/foi-flow#427]
startupProbe:
            httpGet:
              path: /api/v1/configs
              port: 7085
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 10

**Describe the bug in current situation**
The Angular FOI form started failing on Aug 28th and 29th (the weekend).

After some preliminary investigation we found it was failing the readiness checks and startup probes, which caused OpenShift to think it's failing.  Strangely, the application seems fine, but for some reason it fails the probes.  If we remove the probes the application starts up fine, and we can even access the urls that the probe fails on.

As a temporary solution we've disabled the readiness probes.  Many projects don't even bother with these so in one sense we're fine; but the readiness probes work in TEST.  We do not want our TEST and DEV environments to diverge, so we should investigate this and come up with a solution that brings DEV/TEST in line.

Problem code removed from the Angular app's API yaml.       

```
          readinessProbe:
            httpGet:
              path: /api/v1/configs
              port: 7085
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
... snip ....

        startupProbe:
            httpGet:
              path: /api/v1/configs
              port: 7085
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 10
````

Compare to test environment to see location.

**Link bug to the User Story**

**Impact of this bug**
Low impact, but this leads to accruing tech-debt.

As I said, many projects don't even setup readiness probes and they're fine.  In our case they're a bonus feature and not necessary.  The main problem is finding the underlying issue as to why our dev and test environments diverged over the weekend.  

**Chance of Occurring (high/medium/low/very low)**
NA.  Issue is currently always in effect, but it doesn't affect end-users.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

Only happens in DEV.

**Steps to Reproduce**
1. Re-enable both readiness/startup probes
2. Watch build fail into CrashLoopBackoff - even though logs show it booted healthily.

**Actual/ observed behaviour/ results**
Probes fail on dev, but not test.

**Expected behaviour**
Probes behave the same on dev and test.
